# -*- coding: utf-8 -*-
"""visual question and answering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrc-TsvfhZo2R_2twC5l5j5excHg1FaD
"""

!pip install transformers

from transformers import pipeline

vqa_pipeline = pipeline('visual-question-answering')

image = r'/content/E1.jpg'

question = input("enter a question to ask about image:")
result = vqa_pipeline(image, question)
print(result,end=" ")

